theme = "kinda_nvim"

[editor]
color-modes = true
completion-replace = true
completion-timeout = 5
cursorline = true
default-yank-register = "+"
end-of-line-diagnostics = "hint"
text-width = 120
trim-final-newlines = true
trim-trailing-whitespace = true
true-color = true
undercurl = true

[editor.lsp]
display-progress-messages = true

[editor.auto-save]
focus-lost = true
after-delay.enable = true
after-delay.timeout = 30000

[editor.statusline]
center = ["version-control"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.inline-diagnostics]
cursor-line = "warning"

[keys.select]
0 = "goto_line_start"
"$" = "goto_line_end"
"^" = "goto_first_nonwhitespace"
G = "goto_file_end"
D = ["extend_to_line_bounds", "delete_selection", "normal_mode"]
k = ["extend_line_up", "extend_to_line_bounds"]
j = ["extend_line_down", "extend_to_line_bounds"]

[keys.normal]
D = ["ensure_selections_forward", "extend_to_line_end", "delete_selection"]
0 = "goto_line_start"
"$" = "goto_line_end"
"^" = "goto_first_nonwhitespace"
G = "goto_file_end"
V = ["select_mode", "extend_to_line_bounds"]
esc = ["collapse_selection", "keep_primary_selection"]

[keys.normal."+"]
f = ":format"
w = ":toggle whitespace.render none all"
r = ":reload-all"
